const fs = require('fs');
const path = require('path');

const imagesDir = path.join(__dirname, '../entities/housing/api/images');
const dataPath = path.join(__dirname, '../entities/housing/api/housing.data.json');
const outMapPath = path.join(__dirname, '../entities/housing/api/images.ts');

let housingData = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

// 1. Gather all images
let imageMapEntries = [];
function walkDir(dir, prefix = '') {
  const files = fs.readdirSync(dir);
  for (const file of files) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat.isDirectory()) {
      walkDir(fullPath, prefix + file + '/');
    } else if (file.match(/\.(webp|jpe?g|png)$/i)) {
      const relPath = prefix + file;
      imageMapEntries.push(`  "${relPath}": require("./images/${relPath}"),`);
    }
  }
}
if (fs.existsSync(imagesDir)) {
  walkDir(imagesDir);
}

// 2. Generate images.ts
const mapContent = `// Auto-generated by generate_images_map.js
export const HousingImages: Record<string, any> = {
${imageMapEntries.join('\n')}
};
`;
fs.writeFileSync(outMapPath, mapContent, 'utf8');

// 3. Update housing.data.json
housingData = housingData.map(item => {
  const newImages = (item.images || []).map(img => {
    // If it's a full path, extract the id/filename part
    const match = img.match(/images[/\\]([^/\\]+[/\\][^/\\]+)$/);
    if (match) {
      // replace backslashes with forward slashes
      return match[1].replace(/\\\\/g, '/').replace(/\\/g, '/');
    }
    return img;
  });

  let features = item.features || [];
  if (features.length === 0 && item.description) {
    const AMENITY_KEYWORDS = [
      ['Piscina',      /piscina/i],
      ['Gimnasio',     /gimnasio|gym/i],
      ['Parrilla',     /parrilla|bbq|barbacoa/i],
      ['Estacionamiento', /cochera|estacionamiento|parking/i],
      ['Amoblado',     /amoblado|amueblado/i],
      ['Seguridad 24/7', /vigilancia|seguridad|guardia/i],
      ['Coworking',    /coworking/i],
      ['Ascensor',     /ascensor/i],
      ['Balcón',       /balcón|balcon/i],
      ['Áreas comunes',/áreas comunes|areas comunes/i],
      ['Pet Friendly', /mascota|pet.friendly/i],
      ['Gas natural',  /gas natural|calidda/i],
      ['Terraza',      /terraza/i],
      ['Vista al mar', /vista al mar/i],
    ];
    for (const [label, re] of AMENITY_KEYWORDS) {
      if (re.test(item.description) && features.length < 5) features.push(label);
    }
    if (features.length === 0) features.push('Edificio moderno');
  }

  let price = item.price;
  let currency = item.currency || 'PEN';
  if (price === null || price === undefined) {
    price = item.total_area_sqm ? Math.round(item.total_area_sqm * 30) : 1500;
  }
  
  if (item.latitude === null || item.latitude === undefined) {
    item.latitude = -12.0464;
  }
  if (item.longitude === null || item.longitude === undefined) {
    item.longitude = -77.0428;
  }

  return {
    ...item,
    images: newImages,
    features,
    price,
    currency
  };
});

fs.writeFileSync(dataPath, JSON.stringify(housingData, null, 2), 'utf8');
console.log('✅ Generated images.ts and updated housing.data.json');
